config/routes.rb
Rails.application.routes.draw do

  get '/register'  => 'register#index'
  post '/register' => 'register#create'
  post '/session'  => 'session#create'
  delete '/logout' => 'session#delete'
  post '/home'     => 'home#index'
  post '/messages' => 'messages#create'
  get '/messages/:id'  => 'messages#check'
  get '/messages/more/:count'  => 'messages#more'
  get '/users/check'  => 'users#check'

  resources :users, only: [:index, :show]

  namespace :admin do
    get '/dashboard' => 'dashboard#index'

    resources :users
    resources :messages, only: [:index, :show]
  end

  root 'welcome#index'

end



#table_name: users
#model_name: User
#routes:

#  GET /users          ----> list many users
#  POST /users         ----> create user
#  GET /users/ID       ----> show 1 user
#  GET /users/ID/edit  ----> edit 1 user
#  PUT /users/ID       ----> update 1 user
#  DELETE /users/ID    ----> delete 1 user

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :user
  validates :main_message, :presence => true
  validates :user_id, :presence => true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :messages
  validates :first_name, :presence => true
  validates :last_name, :presence => { :message => 'Input last name.' }
  validates :username, :presence => { :message => 'Input username.' }, length: { minimum: 3 }, uniqueness: true
  validates :password, :presence => { :message => 'Input password.' }

  def name
    self.first_name+" "+self.last_name
  end
end

app/controllers/admin/dashboard_controller.rb
module Admin
  class DashboardController < ApplicationController
    before_filter :require_admin

    def index
    end

    private

    def require_admin
      redirect_to root_path if current_user.nil? || !current_user.is_admin
    end
  end
end

app/controllers/admin/messages_controller.rb
module Admin
  class MessagesController < ApplicationController
    before_filter :require_admin

    def index
      @messages = Message.all
    end

    def show
      @message = Message.find(params[:id])
    end

    private

    def require_admin
      redirect_to root_path if current_user.nil? || !current_user.is_admin
    end
  end
end

app/controllers/admin/users_controller.rb
module Admin
  class UsersController < ApplicationController
    before_filter :require_admin

    def index
      @users = User.all
    end

    def edit
      @user = User.find(params[:id])
    end

    def update
      @user = User.find(params[:id])
      if @user.update_attributes(user_params)
        redirect_to admin_users_path
      else
        render 'edit'
      end
    end

    def user_params
      params.require(:user).permit!
    end

    def destroy
      User.find(params[:id]).destroy
      flash[:success] = "User deletion succesful."
      redirect_to admin_users_path
    end

    private

    def require_admin
      redirect_to root_path if current_user.nil? || !current_user.is_admin
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user

  def current_user
    if session
      User.where(:id => session[:user_id]).first
    end
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def create
    @message = Message.new(message_params)
    if @message.save
      respond_to do |format|
        format.html do
          redirect_to root_url
        end

        format.json do
          render :json => @message, :include => :user
        end
      end
    else
      render :index
    end
  end

  def message_params
    params.require(:message).permit!
  end

  def check
    if params[:id] != Message.last.id.to_s
      @new_messages = Message.where("id > ?", params[:id])
      render :json => @new_messages, :include => :user
    else
      render :json => ""
    end
  end

  def more
    @more_messages = Message.last(params[:count])
    render :json => @more_messages, :include => :user
    # render :text => params[:count]
  end
end

app/controllers/register_controller.rb
class RegisterController < ApplicationController
  def index
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "User successfully created."
      redirect_to root_url
    else
      render :index
    end
  end

  def user_params
    params.require(:user).permit!
  end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def create
    user = User.where({:username => params[:user][:username]}).first
    if user && user.password == params[:user][:password]
      session[:user_id] = user.id
      flash[:success] = "Succesfully signed in."
      redirect_to root_path
    else
      flash[:error] = "Invalid username/password."
      redirect_to root_path
    end
  end

  def delete
    session[:user_id] = nil
    flash[:success] = "Succesfully logged out."
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :require_user

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def dashboard
  end

  def check
    @user = User.where(:id => current_user.id).first
    @user.update_attributes(:last_online_at => DateTime.now)
    # @users = User.where("last_online_at > ?", DateTime.now.in_time_zone-5)
    @users = User.where(["id != ? AND last_online_at > ?", current_user.id, DateTime.now-5.minutes])
    render :json => @users
    # if params[:id] != Message.last.id.to_s
    #   @new_messages = Message.where("id > ?", params[:id])
    #   render :json => @new_messages, :include => :user
    # else
    #   render :json => ""
    # end
  end

  private

  def require_user
    redirect_to root_path if current_user.nil?
  end
end

#User.last.update(:is_admin => true)

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @session = User.new
    @message = Message.new
    @messages = Message.last(10)
    if current_user
      @users = User.where(["id != ? AND last_online_at > ?", current_user.id, DateTime.now-5.minutes])
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_type_to_bootstrap(flash_type)
    case flash_type
    when "error"
      "danger"
    else
      "success"
    end
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/admin/dashboard/index.html.erb
<div class="container">
  <h1>Dashboard</h1>
  <div class="row">
    <div class="col-md-3">
      <ul class="nav nav-pills nav-stacked">
        <li role="presentation" class="active">
          <%= link_to 'Home', admin_dashboard_path %>
        </li>
        <li role="presentation">
          <%= link_to 'Users', admin_users_path %>
        </li>
        <li role="presentation">
          <%= link_to 'Messages', admin_messages_path %>
        </li>
      </ul>
    </div>
    <div class="col-md-9">
      <h1>Welcome Admin!</h1>
    </div>
  </div>
</div>

app/views/admin/messages/index.html.erb
<div class="container">
  <h1>Dashboard</h1>
  <div class="row">
    <div class="col-md-3">
      <ul class="nav nav-pills nav-stacked">
        <li role="presentation">
          <%= link_to 'Home', admin_dashboard_path %>
        </li>
        <li role="presentation">
          <%= link_to 'Users', admin_users_path %>
        </li>
        <li role="presentation" class="active">
          <%= link_to 'Messages', admin_messages_path %>
        </li>
      </ul>
    </div>
    <div class="col-md-9">
      <table class="table">
        <thead>
          <tr>
            <th>Sender</th>
            <th>Message</th>
            <th>Action</th>
          </tr>
        </thead>
        <tbody>
          <% @messages.each do |m| %>
            <tr>
              <td><%= m.user.name %></td>
              <td><%= m.main_message %></td>
              <td>
                <%= link_to 'View', admin_message_path(m.id), :class => 'btn btn-default' %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/admin/messages/show.html.erb
<div class="container">
  <h1>Dashboard</h1>
  <div class="row">
    <div class="col-md-3">
      <ul class="nav nav-pills nav-stacked">
        <li role="presentation">
          <%= link_to 'Home', admin_dashboard_path %>
        </li>
        <li role="presentation">
          <%= link_to 'Users', admin_users_path %>
        </li>
        <li role="presentation" class="active">
          <%= link_to 'Messages', admin_messages_path %>
        </li>
      </ul>
    </div>
    <div class="col-md-9">
      <div class="col-sm-8">
        <h2>View Message</h2>
        <div class="panel panel-default">
          <div class="panel-heading">
            <h3 class="panel-title">Message</h3>
          </div>
          <div class="panel-body">
            <%= @message.main_message %>
          </div>
        </div>
        <div class="panel panel-default">
          <div class="panel-heading">
            <h3 class="panel-title">Sender</h3>
          </div>
          <div class="panel-body">
            <%= @message.user.first_name %> <%= @message.user.last_name %>
          </div>
        </div>
        <%= link_to 'Return', admin_messages_path, :class => 'btn btn-default' %>
      </div>
    </div>
  </div>
</div>

app/views/admin/users/edit.html.erb
<div class="container">
  <h1>Dashboard</h1>
  <div class="row">
    <div class="col-md-3">
      <ul class="nav nav-pills nav-stacked">
        <li role="presentation">
          <%= link_to 'Home', admin_dashboard_path %>
        </li>
        <li role="presentation" class="active">
          <%= link_to 'Users', admin_users_path %>
        </li>
        <li role="presentation">
          <%= link_to 'Messages', admin_messages_path %>
        </li>
      </ul>
    </div>
    <div class="col-md-9">
      <div class="col-sm-8">
        <h2>Edit User</h2>
        <%= form_for @user, :url => admin_user_path do |f| %>
          <div class="alert alert-danger" role="alert">
            <%= @user.errors.messages %>
          </div>
          <div class="form-group">
            <%= f.label :first_name %>
            <%= f.text_field :first_name, :class => 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :last_name %>
            <%= f.text_field :last_name, :class => 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :username %>
            <%= f.text_field :username, :class => 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.hidden_field :is_admin, :class => 'form-control' %>
            <%= f.submit :Save, :class => 'btn btn-primary' %>
            <%= link_to 'Cancel', admin_users_path, :class => 'btn btn-default' %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/admin/users/index.html.erb
<div class="container">
  <h1>Dashboard</h1>
  <div class="row">
    <div class="col-md-3">
      <ul class="nav nav-pills nav-stacked">
        <li role="presentation">
          <%= link_to 'Home', admin_dashboard_path %>
        </li>
        <li role="presentation" class="active">
          <%= link_to 'Users', admin_users_path %>
        </li>
        <li role="presentation">
          <%= link_to 'Messages', admin_messages_path %>
        </li>
      </ul>
    </div>
    <div class="col-md-9">
      <table class="table">
        <thead>
          <tr>
            <th>First Name</th>
            <th>Last Name</th>
            <th>Username</th>
            <th>Action</th>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |u| %>
            <tr>
              <td><%= u.first_name %></td>
              <td><%= u.last_name %></td>
              <td><%= u.username %></td>
              <td>
                <%= link_to "Edit", edit_admin_user_path(u.id), :class => "btn btn-default" %>
                <%= link_to "Delete", admin_user_path(u.id), method: :delete,
                    data: {
                      confirm: "Are you sure you want to delete #{u.first_name} #{u.last_name}?"
                    },
                    :class => "btn btn-default" %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Chat App</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div id="container">

    <%= render :partial => "shared/header" %>

    <%= render :partial => "shared/flash" %>

    <%= yield %>

  </div>
</body>
</html>

app/views/register/index.html.erb
<div class="form-register">
  <div class="row">
    <div class="col-sm-4 col-sm-offset-4">

      <h2>Registration Form</h2>

      <%= form_for @user, :url => register_path do |f| %>

          <% if @user.errors.full_messages.any? %>
            <div class="alert alert-danger">
              <% @user.errors.each do |input, message| %>
                <%= input %>: <%= message %>
                <br/>
              <% end %>
            </div>
          <% end %>

        <div class="form-group">
          <%= f.label :first_name %>
          <%= f.text_field :first_name, :class => 'form-control' %>
        </div>

        <div class="form-group">
          <%= f.label :last_name %>
          <%= f.text_field :last_name, :class => 'form-control' %>
        </div>

        <div class="form-group">
          <%= f.label :username %>
          <%= f.text_field :username, :class => 'form-control' %>
        </div>

        <div class="form-group">
          <%= f.label :password %>
          <%= f.password_field :password, :class => 'form-control' %>
        </div>

        <div class="form-group">
          <%= f.submit :Submit, :class => 'btn btn-lg btn-primary btn-block' %>
        </div>

      <% end %>

    </div>
  </div>
</div>

app/views/shared/_flash.html.erb
<% flash.each do |name, msg| %>
  <div class="alert alert-<%= flash_type_to_bootstrap(name) %> text-center">
    <div class="inner_div">
      <%= content_tag :div, msg, id: "flash_#{name}" %>
    </div>
  </div>
<% end %>

app/views/shared/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Chat App</a>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <% if current_user %>
          <li>
            <%=
              if current_user.is_admin == true
                link_to 'Dashboard', admin_dashboard_path, method: :get
              else
                link_to current_user.first_name+" "+current_user.last_name
              end
            %>
          </li>
        <% end %>
        
        <% if current_user %>
          <li><%= link_to "Logout", logout_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Login", root_path, method: :get %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8 col-md-offset-2 users_container">
      <h1>Users</h1>
      <ul class="list-group">
        <% @users.each do |u| %>
          <li class="list-group-item">
            <span class="badge"></span>
            <%= link_to u.first_name+" "+u.last_name, user_path(u.id) %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8 col-md-offset-2">

      <h1>Profile</h1>
        <div class="panel panel-default">
          <div class="panel-heading">
            First Name
          </div>
          <div class="panel-body">
            <%= @user.first_name %>
          </div>
        </div>
        <div class="panel panel-default">
          <div class="panel-heading">
            Last Name
          </div>
          <div class="panel-body">
            <%= @user.last_name %>
          </div>
        </div>
        <div class="panel panel-default">
          <div class="panel-heading">
            Username
          </div>
          <div class="panel-body">
            <%= @user.username %>
          </div>
        </div>
        <%= if current_user.is_admin == true %>
          <div class="btn-group">
            <%= link_to "Go to Users", users_path, :class => "btn btn-default" %>
          </div>
          <div class="btn-group">
            <%= link_to "Go to Messages", messages_path, :class => "btn btn-default" %>
          </div>
        <% else %>
        <div class="btn-group">
          <%= link_to "Go back to Messages", root_path, :class => "btn btn-default" %>
        </div>
        <% end %>
    </div>
  </div>
</div>

app/views/welcome/_logged_in_index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3">
      <h1>Online Users</h1>
      <div class="col-md-12 users_container">
        <ul class="list-group">
          <% @users.each do |u| %>
            <li class="list-group-item">
              <%= u.name %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
    <div class="col-md-9">
      <h1>Messages</h1>
      <div class="col-md-12 messages_container" count=10>
        <% @messages.each do |m| %>
        <% if m.user.id == session[:user_id] %>
          <div class="text-right well well-sm" message_id=<%= m.id %>>
          <strong>You</strong>:
        <% else %>
          <% format = "" %>
          <div class="well well-sm" message_id=<%= m.id %>>
          <%= link_to m.user.name, user_path(m.user_id) %>:
        <% end %>
          <%= m.main_message %>
          </div>
        <% end %>
      </div>
      <div id="user_id" value=<%= current_user.id %>></div>
      <div class="col-md-12">
        <%= form_for @message, :url => messages_path, :remote => true, :data => {:type => "json"}, :html => {:id => "js-message"} do |f| %>
          <%= f.text_area :main_message, :placeholder => 'Input your message here..', :class => "form-control" %>
          <%= f.hidden_field :user_id, :value => session[:user_id] %>
          <% #f.submit :Submit, :class => 'btn btn-primary btn_block form-group' %>
        <% end %>
        <button type="button" id="scroll" name="button" hidden>check scroll</button>
      </div>
    </div>
  </div>
</div>

<script type="text/javascript">
  setInterval(function() {
    var message_id = $(".messages_container div:last-child").attr('message_id');
    $.ajax({
      type: "GET",
      url: "/messages/"+message_id
    }).done(function(new_messages){
      $.each(new_messages, function(key, data){
        var message = $("<div>").text(data.main_message).html();
        $(".messages_container").append(
          "<div class='well well-sm animated bounceIn' message_id='"+data.id+"'>"+
            "<a href='/user/"+data.user_id+"'>"
            +data.user.first_name+" "+data.user.last_name+
            "</a>: "
            +message+
          "</div>"
        ).scrollTop(9999999);
      });
    });

    $.ajax({
      type: "GET",
      url: "/users/check"
    }).done(function(online_users){
      $(".users_container ul").html("");
      $.each(online_users, function(key, data){
        $(".users_container ul").append(
          "<li class='list-group-item'>"+
            data.first_name+" "+data.last_name+
          "</li>"
        );
      });
    });
  }, 5000);
</script>

app/views/welcome/_logged_out_index.html.erb
<div class="form-signin">
  <div class="row">
    <div class="col-sm-4 col-sm-offset-4">

      <h2>Sign in</h2>

      <%= form_for @session, :url => session_path do |f| %>

        <div class="form-group">
          <%= f.label :username %>
          <%= f.text_field :username, :class => 'form-control' %>
        </div>

        <div class="form-group">
          <%= f.label :password %>
          <%= f.password_field :password, :class => 'form-control' %>
        </div>

        <div class="form-group">
          <%= f.submit :Submit, :class => 'btn btn-lg btn-primary btn-block' %>
        </div>

      <% end %>

      <%= link_to "Register", register_path, :class => "btn btn-default" %>

    </div>
  </div>
</div>

app/views/welcome/index.html.erb
<% if current_user %>

  <%= render :partial => "logged_in_index" %>

<% else %>

  <%= render :partial => "logged_out_index" %>

<% end %>

app/views/welcome/new_message.html.erb
<div class="<%= format %> well well-sm" message_id=<%= m.id %>>
  <%= link_to m.user.first_name+" "+m.user.last_name, user_path(m.user_id) %>: <%= m.main_message %>
</div>